# Generated by Django 6.0.2 on 2026-04-04 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "affiliation",
                    models.CharField(
                        choices=[
                            ("undergrad", "Undergrad"),
                            ("grad", "Grad"),
                            ("faculty", "Faculty"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("class_year", models.IntegerField(blank=True, null=True)),
                (
                    "major_department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("bio", models.TextField(blank=True, default="")),
                ("headshot_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="article",
            old_name="submitted_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.RemoveField(
            model_name="article",
            name="status",
        ),
        migrations.AddField(
            model_name="article",
            name="acknowledgements",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="body",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="estimated_read_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="publication_preference",
            field=models.CharField(
                choices=[
                    ("asap", "ASAP"),
                    ("next_issue", "Next Issue"),
                    ("flexible", "Flexible"),
                ],
                default="flexible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="section",
            field=models.CharField(
                choices=[
                    ("technical", "Technical"),
                    ("opinion", "Opinion"),
                    ("creative", "Creative"),
                    ("interview", "Interview"),
                    ("humor", "Humor"),
                    ("spotlight", "Spotlight"),
                ],
                default="technical",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.CharField(
                blank=True, default="", help_text="Comma-separated tags", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="abstract",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.CreateModel(
            name="ArticleAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "external_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "external_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("external_class_year", models.IntegerField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_authors",
                        to="submissions.article",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_authors",
                        to="submissions.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("caption", models.CharField(blank=True, default="", max_length=500)),
                ("alt_text", models.CharField(blank=True, default="", max_length=500)),
                ("credit", models.CharField(blank=True, default="", max_length=255)),
                ("is_cover", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="submissions.article",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.DeleteModel(
            name="ArticleFile",
        ),
    ]
